version: '3'

services:
  fleury-pn:
    build:  ./processing-node
    depends_on:
      - fleury-gd
    environment:
      app.consumer.topics: "AppModel"
      app.consumer.auto.offset.reset: "latest"
      app.consumer.bootstrap.servers: "fleury-kafka1:6110"    # aqui
      app.consumer.group.id: "gw-consumer"
      app.producer.bootstrap.servers: "fleury-kafka1:6110"    # aqui
      app.producer.retries: "3"
      app.producer.enable.idempotence: "true"
      app.producer.linger.ms: "1"
      app.producer.acks: "all"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  fleury-gd:
    build:  ./group-definer
    environment:
      gd.one.consumer.topics: "GroupReportTopic"
      gd.one.consumer.auto.offset.reset: "latest"
      gd.one.consumer.bootstrap.servers: "fleury-kafka1:6110"   # aqui
      gd.one.consumer.group.id: "gw-gd"
      gd.one.producer.bootstrap.servers: "fleury-kafka1:6110"   # aqui
      gd.one.producer.retries: "3"
      gd.one.producer.enable.idempotence: "true"
      gd.one.producer.linger.ms: "1"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
        